spring:
  application:
    name: junyue-server-cron
  datasource:
    url: jdbc:mysql://mysql:3306/junyue-prod?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: C58sqlpjTT4PBkd
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      exclude: static/**,templates/**
    livereload:
      enabled: true
    remote:
      debug:
        enabled: true
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  output:
    ansi:
      enabled: always
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
mybatis:
  # classpath* 此處的* 必須添加 否则会只扫描一个 jar 包，非常重要，2个小时的调试结果。
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.xiaohuodui.model
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
server:
  port: 9002
logging:
  path: /logs/junyue-cron
  level:
    root: info
qr:
  code:
    template: http://47.96.69.184:8080/pages/reserve/reserve?seatId=%d
storage:
  upload:
    path:
clear:
  meeting:
    api:
      url: http://112.124.37.128
      faceUrl: http://112.124.37.128:1888
      username: root@default
      password_md5: e10adc3949ba59abbe56e057f20f883e
bostex:
  face:
    api:
      url: http://10.128.13.244:15000
      appId: xnl
      appKey: xnl
icc:
  api:
    url: icc-dev.hibetatest.com:4077
    clientId: CompanyNames
    clientSecret: 42bec152-8f04-476a-9aec-e7d616ff3cb3
    username: TEST
    password: Admin123
    monitor: http://127.0.0.1:9003/bAdmin/v1/icc/event
api:
  url: http://47.96.69.184:8080
